drop table tmp_t1;
drop table tmp_t2;
drop table tmp_t3;
create table tmp_t1 (i int, f float, c char(10));
create table tmp_t2 (i int, f float, c char(10));
create table tmp_t3 (i int, d date);
load data infile "../test/sql/dataset/t1.csv" into table tmp_t1;
load data infile "../test/sql/dataset/t2.csv" into table tmp_t2;
load data infile "../test/sql/dataset/t3.csv" into table tmp_t3;
select * from tmp_t1 inner join tmp_t2 on tmp_t1.i = tmp_t2.i;
select * from tmp_t2 inner join tmp_t1 on tmp_t1.i = tmp_t2.i;
select * from tmp_t1 inner join tmp_t3 on tmp_t1.i = tmp_t3.i;
select * from tmp_t3 inner join tmp_t1 on tmp_t1.i = tmp_t3.i;
select * from tmp_t2 inner join tmp_t3 on tmp_t2.i = tmp_t3.i;
select * from tmp_t3 inner join tmp_t2 on tmp_t2.i = tmp_t3.i;
select * from tmp_t1 inner join tmp_t2 on tmp_t1.i = tmp_t2.i inner join tmp_t3 on tmp_t1.i = tmp_t3.i;
select * from tmp_t1 inner join tmp_t2 on tmp_t1.i = tmp_t2.i inner join tmp_t3 on tmp_t1.i = tmp_t3.i where tmp_t1.c > "a";
drop table tmp_t1;
drop table tmp_t2;
drop table tmp_t3;
exit;