drop table tmp_t1;
drop table tmp_t2;
drop table tmp_t3;
create table tmp_t1 (i int, f float, c char(10));
create table tmp_t2 (i int, f float, c char(10));
create table tmp_t3 (i int, d date);
load data infile "../test/sql/dataset/t1.csv" into table tmp_t1;
load data infile "../test/sql/dataset/t2.csv" into table tmp_t2;
load data infile "../test/sql/dataset/t3.csv" into table tmp_t3;
select * from tmp_t1;
select * from tmp_t2;
select * from tmp_t3;
select * from tmp_t1, tmp_t2;
select * from tmp_t1, tmp_t3;
select * from tmp_t2, tmp_t3;
select * from tmp_t1, tmp_t2, tmp_t3;
select tmp_t1.*, tmp_t2.i from tmp_t1, tmp_t2;
select tmp_t1.f, tmp_t2.* from tmp_t1, tmp_t2;
select tmp_t2.*, tmp_t1.* from tmp_t1, tmp_t2;
select tmp_t2.c, tmp_t2.f, tmp_t1.f, tmp_t1.c, tmp_t1.i from tmp_t1, tmp_t2;
select * from tmp_t1, tmp_t2 where tmp_t1.i = tmp_t2.i;
select * from tmp_t1, tmp_t2 where tmp_t1.f > tmp_t2.f;
select * from tmp_t1, tmp_t2 where tmp_t1.i = tmp_t2.i and tmp_t1.f > tmp_t2.f;
select tmp_t1.i, tmp_t3.d from tmp_t1, tmp_t3 where tmp_t1.i = tmp_t3.i;
select tmp_t4.i from tmp_t1, tmp_t2;
select * from tmp_t1, tmp_t2 where tmp_t4.i = 4;
select * from tmp_t1, tmp_t2 where tmp_t1.x = tmp_t2.x;
select * from tmp_t1, tmp_t2 where tmp_t2.x = tmp_t1.x;
drop table tmp_t1;
drop table tmp_t2;
drop table tmp_t3;
exit;